name: femvitalis
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2 # Optional for typing effect
  intl: ^0.18.0
  table_calendar: ^3.0.8
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  equatable: ^2.0.7
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/img5.png
    - assets/images/img6.png
    - assets/images/img7.png
    - assets/images/Poppy_seed.jpg
    - assets/images/Chia_seed.jpg
    - assets/images/apple_seed.jpg
    - assets/images/watermelon_seed.jpg
    - assets/images/nutrition1.jpeg
    - assets/images/nutrition2.jpg
    - assets/images/nutrition3.jpeg
    - assets/images/nutrition4.png
    - assets/images/nutrition5.png
    - assets/images/nutrition6.png
    - assets/images/nutrition7.png
    - assets/images/nutrition8.png
    - assets/images/nutrition9.png
    - assets/images/nutrition10.png
    - assets/images/body1.jpeg
    - assets/images/body2.jpeg
    - assets/images/body3.jpeg
    - assets/images/body4.jpeg
    - assets/images/body5.jpeg
    - assets/images/body6.jpeg
    - assets/images/body7.jpeg
    - assets/images/body8.jpeg
    - assets/images/body9.jpeg
    - assets/images/body10.jpeg
    - assets/images/baby1.jpeg
    - assets/images/baby2.jpg
    - assets/images/baby3.jpeg
    - assets/images/baby4.jpeg
    - assets/images/baby5.jpeg
    - assets/images/baby6.jpeg
    - assets/images/baby7.jpeg
    - assets/images/baby8.jpeg
    - assets/images/baby9.jpeg
    - assets/images/baby10.jpeg
    - assets/images/myth1.jpeg
    - assets/images/myth2.jpeg
    - assets/images/myth3.jpeg
    - assets/images/myth4.jpeg
    - assets/images/myth5.jpeg
    - assets/images/myth6.jpeg
    - assets/images/myth7.jpeg
    - assets/images/myth8.jpeg
    - assets/images/myth9.jpeg
    - assets/images/myth10.jpeg
    - assets/images/profile.jpeg
    - 'assets/images/fig.png'
    - 'assets/images/grape.jpg'
    - 'assets/images/raspberry.jpg'
    - 'assets/images/blueberry.png'
    - 'assets/images/kumquat.jpg'
    - assets/images/lime.jpeg
    - assets/images/lemon.jpeg
    - assets/images/peach.jpeg
    - assets/images/apple.png
    - assets/images/avocado.png
    - assets/images/pear.jpeg
    - assets/images/bell_pepper.png
    - assets/images/mango.jpeg
    - assets/images/banana.jpeg
    - assets/images/healthy_breakfast.jpg
    - assets/images/profile1.png
    - assets/images/profile2.png
    - assets/images/carrot.png
    - assets/images/corn.jpeg
    - assets/images/grapefruit.jpeg
    - assets/images/cantaloupe.jpg
    - assets/images/cauliflower.png
    - assets/images/lettuce.png
    - assets/images/cabbage.png
    - assets/images/eggplant.jpeg
    - assets/images/butternut_squash.jpg
    - assets/images/coconut.jpeg
    - assets/images/pineapple.jpeg
    - assets/images/jicama.jpeg
    - assets/images/durian.jpeg
    - assets/images/cantaloupe.jpg
    - assets/images/honeydew.jpeg
    - assets/images/romaine.jpeg
    - assets/images/swiss_chard.jpeg
    - assets/images/leek.jpeg
    - assets/images/watermelon.jpeg
    - assets/images/pumpkin.jpg
    - assets/images/size1.jpg


    - assets/images/week1.jpg
    - assets/images/week2.jpg
    - assets/images/week3.jpg
    - assets/images/week4.jpeg
    - assets/images/week5.jpg
    - assets/images/week6.jpeg
    - assets/images/week7.png
    - assets/images/week8.png
    - assets/images/week9.png
    - assets/images/week10.png
    - assets/images/pcos1.jpg
    - assets/images/size1.jpg
    - assets/images/size3.jpg
    - assets/images/size4.jpg
    - assets/images/size5.jpg
    - assets/images/size6.jpg
    - assets/images/size7.jpg
    - assets/images/size8.jpg

    - assets/images/size9.jpg
    - assets/images/size10.jpg
    - assets/images/size11.jpg
    - assets/images/size12.jpg
    - assets/images/size13.jpg
    - assets/images/size14.jpg
    - assets/images/size15.jpg
    - assets/images/size16.jpg
    - assets/images/size17.jpg
    - assets/images/size18.jpg
    - assets/images/size19.jpg
    - assets/images/size20.jpg
    - assets/images/size21.jpg
    - assets/images/size22.jpg
    - assets/images/size23.jpg
    - assets/images/size24.jpg
    - assets/images/size25.jpg
    - assets/images/size26.jpg

    - assets/images/size27.jpg
    - assets/images/size28.jpg
    - assets/images/size29.jpg
    - assets/images/size30.jpg
    - assets/images/size31.jpg
    - assets/images/size32.jpg
    - assets/images/size33.jpg
    - assets/images/size34.jpg
    - assets/images/size35.jpg
    - assets/images/size36.jpg
    - assets/images/size37.jpg
    - assets/images/size38.jpg
    - assets/images/size39.jpg
    - assets/images/size40.jpg
    - assets/images/pcos2.jpg
    - assets/images/pcos3.png
    - assets/images/pcos4.jpeg
    - assets/images/pcos5.jpg
    - assets/images/pcos6.jpeg
    - assets/images/pcos7.jpg
    - assets/images/pcos8.jpg
    - assets/images/pcos9.jpg
    - assets/images/pcos10.png
    - assets/images/endo1.jpg
    - assets/images/endo2.jpg
    - assets/images/endo3.png
    - assets/images/endo4.jpeg
    - assets/images/endo5.jpeg
    - assets/images/endo6.jpeg
    - assets/images/endo7.png
    - assets/images/endo8.jpg
    - assets/images/endo9.jpg
    - assets/images/endo10.jpeg
    - assets/images/bc1.png
    - assets/images/bc2.png
    - assets/images/bc3.jpg
    - assets/images/bc4.jpeg
    - assets/images/bc5.jpeg
    - assets/images/bc6.png
    - assets/images/bc7.jpeg
    - assets/images/bc8.jpeg
    - assets/images/bc9.jpeg
    - assets/images/bc10.jpeg
    - assets/images/gen1.jpg
    - assets/images/gen2.png
    - assets/images/gen3.jpeg
    - assets/images/gen4.jpeg
    - assets/images/gen5.png
    - assets/images/gen6.png
    - assets/images/gen7.jpg
    - assets/images/gen8.png
    - assets/images/gen9.jpeg
    - assets/images/gen10.jpeg
    - assets/images/breastfeed.jpg
    - 'assets/images/baby.jpg'
    - assets/images/edit.png
    - assets/images/breastfeed.jpg
    - assets/images/bottle.jpg
    - assets/images/diaper.jpg
    - assets/images/food.jpeg


    # Add more images if needed later
    # - assets/images/hands.png
